/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSX_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_Centroid_LL.h"
#include "CapSense_Gesture.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "Blue_LED.h"
#include "Blue_LED_aliases.h"
#include "Red_LED.h"
#include "Red_LED_aliases.h"
#include "Green_LED.h"
#include "Green_LED_aliases.h"
#include "PWM_Green.h"
#include "PWM_Blue.h"
#include "Clock_1.h"
#include "CapSense_ISR.h"
#include "CapSense_TMG.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "cy_em_eeprom.h"
#include "CyLFClk.h"

/*[]*/

